### ISSUE TITLE
How to represent PerceivableQuality, Non-PerceivableQuality and NominalQuality

### ISSUE THREAD

**Issue by andredemori** [OntoUML/ontouml-vp-plugin#104]
I'm trying to represent the three types of Qualities featured on the OntoUML website:  PerceivableQuality, Non-PerceivableQuality and NominalQuality

https://ontouml.readthedocs.io/en/latest/classes/aspects/quality/index.html

I can't find where I define these three types of Qualities, I can only use a generic «Quality» in Visual Piradigm.

Thanks.

**Comment by tgoprince** [comment]
Hi @andredemori 

I assume you are referring to the proposal made by Albuquerque and Guizzardi in:

Albuquerque, A., & Guizzardi, G. (2013). [An ontological foundation for conceptual modeling datatypes based on semantic reference spaces.](https://nemo.inf.ufes.br/wp-content/papercite-data/pdf/an_ontological_foundation_for_conceptual_modeling_datatypes_based_on_semantic_reference_spaces_2013.pdf) In IEEE 7th International Conference on Research Challenges in Information Science (RCIS) (pp. 1-12). IEEE

We decided not to officially incorporate that proposal in OntoUML, since it was considered by most users as too complex for the additional expressivity it brought. Instead, we decided to simply stick with the «quality» stereotype.

I'll ask our colleagues to update the documentation you linked in your post.

If you have any modeling questions, please create a new post about it.
