### ISSUE TITLE
Suggestion for creating a Derivation relationship to Relators

### ISSUE THREAD

**Issue by andredemori** [OntoUML/ontouml-vp-plugin#115]
In the process of creating Relators, when there is a material relationship between the parties associated with the Relator, there is also a derivation relationship between the Relator and the material relationship, as shown below:

![Captura de tela de 2021-09-27 21-24-27](https://user-images.githubusercontent.com/10273317/135002708-f5efc65d-8079-49b5-9072-d9064c1e20eb.png)

Currently, to represent the derivation relationship it is necessary to use the 'Association Class' of Visual Paradigm. Nevertheless, users may find that the relationship that exists between the Relator and the material relationship is not a derivation, but that the Relator is an association class. There should be a clear distinction between Association Class and Derivation.

The suggestion is that when right-clicking on the Association Class relation that links the Relator to the material relation, the Derivation option would appear in 'Suggested Stereotypes' so that this Association Class could be transformed into a derivation relation.

**Comment by claudenirmf** [comment]
Thanks for your message, @andredemori! User feedback is more than welcome.

Still, we must be really careful about adding stereotypes to OntoUML's UML profile because that is a modification in the language itself. Even though we take advantage of UML's association class syntax, there is no other application of dashed lines between classes and associations if not derivation. In other words, a stereotype would be redundant at the moment.

So, I will be closing the issue for now, but feel free add new comments.
