### ISSUE TITLE
Problem with Protege opening .ttl file  

### ISSUE THREAD

**Issue by AndrasKomaromi** [OntoUML/ontouml-vp-plugin#120]
Hi, I converted the attached .vpp file with the default options.
I tried to open with Protege but gives a parse error:
![image](https://user-images.githubusercontent.com/93617314/139946638-25a8d4c3-7fdf-43db-ad94-60b46113c633.png)
[1.1-Plato-Models.zip](https://github.com/OntoUML/ontouml-vp-plugin/files/7463737/1.1-Plato-Models.zip)

Could you please help.
Thanks

**Comment by claudenirmf** [comment]
Hi @AndrasKomaromi! Your model contained stereotypes incorrect stereotypes from the point of view of the plug-in (e.g., `«Mediation»` instead of `«mediation»`). As we are still incorporating syntactical verification of associations, this error was not detected automatically. The attached files should be working.

[1.1-Plato-Models.zip](https://github.com/OntoUML/ontouml-vp-plugin/files/7473998/1.1-Plato-Models.zip)

If the issue persists, please let me know so we re-open the issue or create a new one.

**Comment by claudenirmf** [comment]
Sorry, I believe I sent you the project file before saving it.

[1.1-Plato-Models.zip](https://github.com/OntoUML/ontouml-vp-plugin/files/7474173/1.1-Plato-Models.zip)

**Comment by AndrasKomaromi** [comment]
Thank you very much Claudenir, it is working now!
