### ISSUE TITLE
ERROR: Prohibited generalization: Mixing not allowed as supertype of Quality

### ISSUE THREAD

**Issue by plbt5** [OntoUML/ontouml-vp-plugin#152]
Using VP OntoUML plugin version 0.5.3, I get an error when subclassing a Mixin into a Quality. This is explicitly allowed by the [ontoUML documentation](https://ontouml.readthedocs.io/en/latest/classes/aspects/quality/index.html)

ERROR: Prohibited generalization: incompatible 'restrictedTo' values The allowed ontological natures of instances of Class5 are not among the allowed ontological natures of its superclass Class4

<img width="556" alt="image" src="https://github.com/OntoUML/ontouml-vp-plugin/assets/8479553/1f54394c-89cb-4965-9369-cdc7e0aa4a9e">

**Comment by claudenirmf** [comment]
Hi @plbt5!

In OntoUML, the non-sortal classes (i.e., `«mixin»`, `«category»`, `«roleMixin»`, `«phaseMixin»`, and `«historicalMixin»`) can be specialized by classes of different ontological natures. For example, you can have a `«mixin»` that classifies both objects (e.g., cars) and relational entities (e.g., employment), like `Insurable Item`.

![Screenshot 2023-10-12 at 10 57 45](https://github.com/OntoUML/ontouml-vp-plugin/assets/12445213/c27106a1-d215-475d-ae2a-32fd5e8db422)

For this reason, it is necessary to specify what are the possible natures for the instances of a non-sortal, otherwise, you will incur an error if the natures are different between the super-class and the subclass. To make this modification, you can right-click the class and use the _Restrict Ontological Nature_ option.

![Screenshot 2023-10-12 at 10 37 35](https://github.com/OntoUML/ontouml-vp-plugin/assets/12445213/188aef6b-5ff4-4b21-ba37-3b1e5cc622a5)

Since this property is hidden due to the limitations in UML's syntax (which is extended by OntoUML), the automatic color-coding serves as a hint to the value of this `restrictedTo` property (i.e., the property that registers the allowed ontological natures of the class' instances).

- pink: functional-complex (object), collective, or quantity
- green: relator
- blue: quality or mode
- yellow: event
- orange: situation
- purple: type
- white: abstract, datatype, or enumeration

Notice that gray is used whenever there is no value set or there are multiple values related to different colors. In the plugin's _Settings_ menu you can also disable the automatic coloring (_Smart Paint_) and other automated checks that restrict the menu.

I believe I have answered your query, so I am closing this issue. Feel free to keep commenting, so we can open it again if necessary.

**Comment by claudenirmf** [comment]
Thanks, that is really appreciated. We will certainly reach out for that.

At the moment I am focused on developer tools and documentation, which should facilitate us increasing our development team. We will follow that with user documentation and guides.

If you are interested in gUFO as well, I must say that, in my opinion, gUFO is our best-documented resource at the moment.
