### ISSUE TITLE
How to solve "The class X is missing the 'allowed' natures meta-property."

### ISSUE THREAD

**Issue by brunogcarneiro** [OntoUML/ontouml-vp-plugin#82]
Hello

When trying to check a gUFO model the OntoUML output console displayed some erros:

"The class X is missing the 'allowed' natures meta-property."

What does it means?

**Comment by claudenirmf** [comment]
Hi @brunogcarneiro, could you please tell us which version of the plugin you have installed on Visual Paradigm? Have you recently updated the plugin you are using?

In order to use the model transformation, your model (or the part of the model you are trying to transform) cannot have any syntactical errors.

This specific error refers to a class missing a meta-property (a.k.a. tagged value in UML) "restrictedTo" that we have introduced in the language in the previous updates. The model you have was probably developed with a previous version of the plugin and that is why the class has the stereotype but lacks the associated meta-property.

The easiest way to fix this issue is to apply again to the class the same stereotype it already has. This will correctly add to the class the meta-property.

In case the class is specialized by something other than an object class/functional-complex, and the class has one of the following stereotypes «category», «mixin», «phaseMixin», «roleMixin», or «historicalRoleMixin», you will need to update the value of "restrictedTo" by right-clicking the class and going to _Meta-Properties > Restrict Ontological Nature_.

TIP: you can select multiple classes or associations in order to apply the same stereotype or change some meta-property to all of them at once.

Have in mind that we are constantly working to improve our tools and it is important to be up-to-date with our latest release to be sure that everything is working correctly.

**Comment by brunogcarneiro** [comment]
Hello @claudenirmf !

I am getting this error message: "Incompatible allowed natures. The <<role>> class Criterion has 'allowed' natures incompatible with its stereotype. For this stereotypes, the compatible natures are: collective, functional-complex, intrinsic-mode, extrinsic-mode, quality, quantity, relator".

The class <<role>>Criterion specializes the class <<type>>Intrinsic Moment Type. 

The stereotype <<role>> should not accept the nature type too?

**Comment by claudenirmf** [comment]
At the moment we are not supporting the specialization of «type» classes into «subkind», «phase», or «role» in order to provide full compatibility with [gUFO](http://purl.org/nemo/gufo#).

You should convert the class `Criterion` to «role» for the moment.

Also, could you confirm which version of the plugin you are using? If you are in the latest version, you can right-click the class `Criterion` and go to _Suggested Stereotypes_ where _Type_ should be the only enabled option (due to the specialization of the «type» class `Intrinsic Moment Type`).

In addition, bear in mind that when exporting your model to gUFO, `Intrinsic Moment Type` will also be exported. This may be an issue depending on your application. I would avoid adding UFO-A concepts to OntoUML models whenever possible.

**Comment by brunogcarneiro** [comment]
Thank you for the suggestion!

I am using the plugin version 0.4.0.
