### ISSUE TITLE
Organization of the plugins in pom.xml does not work in Eclipse.

### ISSUE THREAD

**Issue by guidoni** [OntoUML/ontouml-vp-plugin#99]
The necessary plugins for the project are found outside the `<pluginManagement>` tag. 

This generates the following error in Eclipse: "Plugin execution not covered by lifecycle configuration: com.coveo: fmt-maven-plugin: 2.10: format (execution: default, phase: process-sources)".

This problem is solved by placing all pluginds inside the pluginManagement tag: `<pluginManagement> .... </pluginManagement>`

**Comment by claudenirmf** [comment]
Did you try running Visual Paradigm from the terminal (see [Developer Instructions](https://github.com/OntoUML/ontouml-vp-plugin#developer-instructions))? I wonder if that is a Windows-related issue or if you are calling Maven using something other than `mvn install exec:exec` (to do this you have to right-click the project and go to _Run As... > Maven build..._ and set the goals as `install exec:exec`). On MacOS, I was able to run Maven just fine.

What confuses me from your solutions, actually, is that the tags `<plugins>` and `<pluginManagement>` have distinct roles, so I don't you how you were able to solve it 😅

**Comment by matheuslenke** [comment]
I was able to run the plugin on Windows with Eclipse using the instructions provided by @claudenirmf without making any changes to the <plugins> tag. I believe this could be an bug with an older version of eclipse. If this issue is persistent, please reopen this bug with more info about your operational system, eclipse and Visual Paradigm versions
